### ISSUE TITLE
Stopwatch Activity Design"FINISH"

### ISSUE THREAD

**Issue by PiranitaGomez** [KUASE-AndroidDev2020/Project04#1]
お疲れ様です。
デザイン基礎の授業では大変お世話になっております。
工学部　1年　諸田紘一です。
さて、6月にご依頼のありました、stopwatch作業が終了いたしましたので、
下記の通り、ご報告いたします。
 
場所：国際学生寮
作業内容：stopwatchのstart,stop,lap,resetを正常に動かすこと。また、そのデザイン。
検証状況：ご担当の又吉様、田中様と共に、動作確認を実施し、問題なく使用できることを確認済みです。
 なお、作業実施にともない、Liang様ご了解のもと、
 Githubにデータを載せております。
 
以上、ご報告いたします。
ご不明の点、あるいは不具合などありましたら、
サポート部(2020ｍ086)までご連絡ください。

**Comment by PiranitaGomez** [comment]
Bug found: after clicking the Reset button, if I click the Lap button before clicking the Start button, timerLabel shows me some random lap time. Then if click the Lap button again, timerLabel shows 0; then if I click the Start button and then click the Lap button, bomb! timerLabel "explodes"~  

Correct app behavior: after clicking the Reset button, if I click the Lap button before clicking the Start button, nothing should show up in timerLabel

**Comment by morotamorota** [comment]
I have look into it and maybe fix the problems. If there's any more problem I will fix it.

**Comment by PiranitaGomez** [comment]
Well done! Thank you for your hard work :)
